const USER_ENDPOINT = '/users';
const LOGIN_ENDPOINT = '/users/login'
const LOGOUT_ENDPOINT = '/users/logout'
const PROFILE_ENDPOINT = `/editUser/`
const FORGOT_PASSWORD_ENDPOINT = '/forgotPassword'
const CHANGE_PASS_ENDPOINT = '/resetPassword/'
const EMAIL_ENDPOINT = '/isEmailUsed'
const CHANGE_ENDPOINT = '/mentor';
const CHANGE_EMAIL_ENDPOINT = '/changeEmail';

export {
  USER_ENDPOINT,
  LOGIN_ENDPOINT,
  LOGOUT_ENDPOINT,
  PROFILE_ENDPOINT,
  FORGOT_PASSWORD_ENDPOINT,
  CHANGE_PASS_ENDPOINT,
  EMAIL_ENDPOINT,
  CHANGE_ENDPOINT,
  CHANGE_EMAIL_ENDPOINT 
}
